brand:
  name: Jymyu
menu-string: Menu

nav:
  - title: Services
    url: '#services'
 
  - title: Who am I?
    url: '#team'
  - title: Story line
    url: '#about'

copyright: Copyright &copy; Your Website 2018

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/JooParreira13' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/joao.parreira.165'
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/jo%C3%A3o-parreira-16a532a1'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
